export enum PurposeOfMeetEnum {
  TO_CHAT_AND_MEET_NEW_PEOPLE = 'TO_CHAT_AND_MEET_NEW_PEOPLE',
  TO_DATE = 'TO_DATE',
  TO_DATE_SERIOUSLY = 'TO_DATE_SERIOUSLY',
  TO_FIND_FRIENDS = 'TO_FIND_FRIENDS',
  TO_SEE_WHAT_HAPPENS = 'TO_SEE_WHAT_HAPPENS',
  TO_SEX = 'TO_SEX'
}
